[18/03/2017] Com quantas views se faz uma APP?
CocoaHeadsBrasil/equinociOS pull request #180
Opened 2017-03-17 00:39 UTC by ronanrodrigo

Eu alterei o título inicial da publicação. Mudei um pouco o foco mas o conteúdo é praticamente o mesmo.

2017-03-17 12:55 UTC, marcelofabri requested changes

2017-03-17 12:55 UTC, marcelofabri commented on _posts/2017-03-18-com-quantas-views-se-faz-um-APP.md
> +Tanto meus primeiros passos dentro do XCode quanto alguns trabalhos profissionais foram feitos com o Storyboard. Eu não conseguia imaginar como alguém em sã consciência poderia substituir o arraste e
Xcode

2017-03-17 13:03 UTC, ronanrodrigo commented on _posts/2017-03-18-com-quantas-views-se-faz-um-APP.md
> +Tanto meus primeiros passos dentro do XCode quanto alguns trabalhos profissionais foram feitos com o Storyboard. Eu não conseguia imaginar como alguém em sã consciência poderia substituir o arraste e
Done 😄

2017-03-17 15:09 UTC, dbonates commented on _posts/2017-03-18-com-quantas-views-se-faz-um-APP.md
> +Pra fazer o layout do card referente ao plano Senior utilizarei um design pattern chamado Dependency Injection. Onde ao invés do nosso componente ter instruções de como se apresentar, eu terei uma cl
> utilizarei um design pattern chamado Dependency Injection. Onde ao invés 

eu eliminaria o ponto e colocaria uma vírgula:

...utilizarei um design pattern chamado Dependency Injection, onde ao invés...

bom artigo, parabéns ;)

2017-03-17 15:09 UTC, dbonates commented on _posts/2017-03-18-com-quantas-views-se-faz-um-APP.md
> +Pra fazer o layout do card referente ao plano Senior utilizarei um design pattern chamado Dependency Injection. Onde ao invés do nosso componente ter instruções de como se apresentar, eu terei uma cl
> , eu terei uma classe que vai posicionar cada elemento no seu lugar. E um objeto da classe BusinessCardComponents vai ser passado através da injeção de dependência

acho que ficou um pouco redundante... poderia ser algo assim, o que acha:

"...eu terei um objeto da classe BusinessCardComponents vai ser passado através da injeção de dependência e que vai posicionar cada elemento no seu lugar."

2017-03-17 15:28 UTC, ronanrodrigo commented on _posts/2017-03-18-com-quantas-views-se-faz-um-APP.md
> +Pra fazer o layout do card referente ao plano Senior utilizarei um design pattern chamado Dependency Injection. Onde ao invés do nosso componente ter instruções de como se apresentar, eu terei uma cl
Se eu trocar por vírgula vai ficar uma frase muito grande. Eu mudei o parágrafo como um todo. O que tu acha?

> Pra fazer o layout do card referente ao plano Senior utilizarei o design pattern  Dependency Injection. O objeto que será injetado vai ser um `BusinessCardComponents` que vai receber instruções de apresentação na `SeniorBusinessCardView`.

2017-03-17 15:28 UTC, ronanrodrigo commented on _posts/2017-03-18-com-quantas-views-se-faz-um-APP.md
> +Pra fazer o layout do card referente ao plano Senior utilizarei um design pattern chamado Dependency Injection. Onde ao invés do nosso componente ter instruções de como se apresentar, eu terei uma cl
Que acabou ficando parecido com o seu segundo comentário, que demorei à ler :P

2017-03-18 16:14 UTC, merged

2017-03-18 17:44 UTC, ronanrodrigo commented
Obrigado @dbonates e @marcelofabri pelas reviews 👍